### ISSUE TITLE
Tracking Issue: Features

### ISSUE THREAD

**Issue by s1gr1d** [getsentry/dev-hub#1]
```[tasklist]
### New Features
- [ ] Display issue description (content)
- [ ] Make Auth better
```

```[tasklist]
### Fixes
- [ ] Add current table filter as url param
- [ ] Fix: Not all issues are shown when filtering for "all"
```
